[project]
name = "globeco-benchmark-coordinator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gevent>=25.5.1",
    "greenlet>=3.2.4",
    "jupyterlab>=4.4.5",
    "kr8s>=0.20.10",
    "locust>=2.37.14",
    "minio>=7.2.16",
    "numpy>=2.3.1",
    "pandas>=2.3.1",
    "paramiko>=4.0.0",
    "prometheus-api-client>=0.6.0",
    "pyarrow>=21.0.0",
]
