[project]
name = "globeco-benchmark-coordinator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.5",
    "locust>=2.37.14",
    "numpy>=2.3.1",
    "pandas>=2.3.1",
]
