apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: globeco-benchmark-coordinator

resources:
- deployment.yaml
- service.yaml
- service-internal.yaml

commonLabels:
  app: globeco-benchmark-coordinator 