apiVersion: v1
kind: Service
metadata:
  name: globeco-benchmark-coordinator-external
  namespace: globeco
  labels:
    app: globeco-benchmark-coordinator
    type: external
spec:
  type: NodePort
  ports:
  - port: 8089
    targetPort: 8089
    nodePort: 30089
    protocol: TCP
    name: http
  - port: 9646
    targetPort: 9646
    nodePort: 30946
    protocol: TCP
    name: metrics
  selector:
    app: globeco-benchmark-coordinator 