apiVersion: v1
kind: Service
metadata:
  name: globeco-benchmark-coordinator-internal
  namespace: globeco
  labels:
    app: globeco-benchmark-coordinator
    type: internal
spec:
  type: ClusterIP
  ports:
  - port: 8089
    targetPort: 8089
    protocol: TCP
    name: http
  - port: 9646
    targetPort: 9646
    protocol: TCP
    name: metrics
  selector:
    app: globeco-benchmark-coordinator 